
(define-abbrev-table 'global-abbrev-table '(
    ("9d" "diferansiyel" nil 1)
    ("9e" "e^{}" move-back-one-char 0)
    ("9n" "\\underbar{}" move-back-one-char 0)    
    ("9f" "formul" nil 1)
    ("9fo" "fonksiyonu" nil 1)
    ("9fr" "\\frac{}{}" move-back-three-chars 0)
    ("9i" "^{-1}" nil 1)
    ("9g" "goruldugu" nil 1)
    ("9l" "_{}^{}" move-back-four-chars 0)
    ("9L" "\\mathcal{L}\\bigg( \\bigg)" move-back-seven-chars 0)
    ("9u" "ustteki" nil 1)
    ("9U" "Ustteki" nil 1)
    ("9o" "o zaman" nil 1)
    ("9O" "O zaman" nil 1)
    ("9p" "\\frac{\\partial }{\\partial x}" nil 1)
    ))
